import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  const password = await bcrypt.hash("password123", 10);

  const student = await prisma.user.upsert({
    where: { email: "alex.johnson@university.edu" },
    update: {
      password,
      name: "Alex Johnson",
      studentId: "STU-2024-001",
      role: "student",
      semester: "Spring 2025",
      avatarUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBqxmkjWjxLc49aNJYtmynJQXsz8OvJUeRu8TWUiuw6Uy2Ho73Bro1tTb0GnUqcsWZxMjCKEzyoW4JxJ_4wfojI2R4WTNfJA4qJ9hwiW085JlBpSp8pA8HNjF-kvxV9p2IJcpLbYjuc47DWm2NSRIwQp41dJId79wNEruvsQOc55Q5Y9T5D0UI0RQMqITWKRy5cHqXeryqdUEWAjJSTzqAXxn2i-b8fpzQ4r2dFu698LmNxXetGl9Wm2A",
      registeredCredits: 14,
      maxCredits: 18,
      creditLimit: 18,
      registrationDeadline: "Mar 30, 2025",
    },
    create: {
      email: "alex.johnson@university.edu",
      password,
      name: "Alex Johnson",
      studentId: "STU-2024-001",
      role: "student",
      semester: "Spring 2025",
      avatarUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBqxmkjWjxLc49aNJYtmynJQXsz8OvJUeRu8TWUiuw6Uy2Ho73Bro1tTb0GnUqcsWZxMjCKEzyoW4JxJ_4wfojI2R4WTNfJA4qJ9hwiW085JlBpSp8pA8HNjF-kvxV9p2IJcpLbYjuc47DWm2NSRIwQp41dJId79wNEruvsQOc55Q5Y9T5D0UI0RQMqITWKRy5cHqXeryqdUEWAjJSTzqAXxn2i-b8fpzQ4r2dFu698LmNxXetGl9Wm2A",
      registeredCredits: 14,
      maxCredits: 18,
      creditLimit: 18,
      registrationDeadline: "Mar 30, 2025",
    },
  });

  const admin = await prisma.user.upsert({
    where: { email: "admin@courseflow.edu" },
    update: {
      password,
      name: "System Admin",
      studentId: "ADMIN-0001",
      role: "admin",
      semester: "Spring 2025",
      avatarUrl: "",
      registeredCredits: 0,
      maxCredits: 0,
      creditLimit: 0,
      registrationDeadline: "",
    },
    create: {
      email: "admin@courseflow.edu",
      password,
      name: "System Admin",
      studentId: "ADMIN-0001",
      role: "admin",
      semester: "Spring 2025",
      avatarUrl: "",
      registeredCredits: 0,
      maxCredits: 0,
      creditLimit: 0,
      registrationDeadline: "",
    },
  });

  const coursesData = [
    // ── Computer Science — Sem 1 ─────────────────────────────
    {
      id: "r001",
      code: "CSC 101",
      name: "Introduction to Computer Science",
      description: "Fundamental concepts of programming and computer systems architecture. Introduction to problem-solving using computers.",
      credits: 4,
      instructor: "Dr. A. Kamau",
      schedule: "Mon/Wed 9:00 AM",
      department: "Computer Science",
      semester: "Sem 1",
      year: 1,
      enrolled: 40,
      capacity: 50,
      colorVariant: "primary",
    },
    {
      id: "c007",
      code: "CSC 103",
      name: "Introduction to Programming",
      description: "Fundamental concepts of procedural programming using Python. Covers variables, control flow, functions, and basic data structures.",
      credits: 3,
      instructor: "Prof. G. Odhiambo",
      schedule: "Mon/Wed 10:00 AM",
      department: "Computer Science",
      semester: "Sem 1",
      year: 1,
      enrolled: 45,
      capacity: 50,
      colorVariant: "primary",
    },
    {
      id: "c001",
      code: "CSC 201",
      name: "Data Structures & Algorithms",
      description: "Fundamental concepts of data structures including arrays, linked lists, stacks, queues, trees, and graphs with algorithm analysis.",
      credits: 3,
      instructor: "Dr. A. Smith",
      schedule: "Tue/Thu 10:00 AM",
      department: "Computer Science",
      semester: "Sem 1",
      year: 2,
      enrolled: 28,
      capacity: 40,
      colorVariant: "secondary",
    },
    {
      id: "csc-s1-net",
      code: "CSC 211",
      name: "Computer Networks",
      description: "Introduction to networking concepts, OSI model, TCP/IP protocols, LAN/WAN technologies, and network security fundamentals.",
      credits: 3,
      instructor: "Dr. P. Wanjiku",
      schedule: "Wed/Fri 11:00 AM",
      department: "Computer Science",
      semester: "Sem 1",
      year: 2,
      enrolled: 32,
      capacity: 45,
      colorVariant: "secondary",
    },
    {
      id: "csc-s1-hci",
      code: "CSC 221",
      name: "Human-Computer Interaction",
      description: "Principles of user interface design, usability testing, accessibility, and user-centered design methodologies.",
      credits: 2,
      instructor: "Ms. F. Achieng",
      schedule: "Thu 2:00 PM",
      department: "Computer Science",
      semester: "Sem 1",
      year: 3,
      enrolled: 38,
      capacity: 40,
      colorVariant: "tertiary",
    },

    // ── Computer Science — Sem 2 ─────────────────────────────
    {
      id: "c004",
      code: "CSC 301",
      name: "Database Systems",
      description: "Relational algebra, SQL, database design, normalisation, transactions, and an introduction to NoSQL databases.",
      credits: 3,
      instructor: "Dr. D. Mwangi",
      schedule: "Fri 9:00 AM",
      department: "Computer Science",
      semester: "Sem 2",
      year: 2,
      enrolled: 18,
      capacity: 40,
      colorVariant: "error",
    },
    {
      id: "c005",
      code: "CSC 310",
      name: "Operating Systems",
      description: "Process management, memory management, file systems, concurrency, and security in modern operating systems.",
      credits: 4,
      instructor: "Prof. E. Mutua",
      schedule: "Tue/Thu 10:00 AM",
      department: "Computer Science",
      semester: "Sem 2",
      year: 2,
      enrolled: 30,
      capacity: 45,
      colorVariant: "secondary",
    },
    {
      id: "csc-s2-ai",
      code: "CSC 320",
      name: "Artificial Intelligence",
      description: "Introduction to AI concepts including search algorithms, knowledge representation, machine learning basics, and expert systems.",
      credits: 3,
      instructor: "Dr. J. Otieno",
      schedule: "Mon/Wed 1:00 PM",
      department: "Computer Science",
      semester: "Sem 2",
      year: 3,
      enrolled: 42,
      capacity: 45,
      colorVariant: "primary",
    },
    {
      id: "csc-s2-sec",
      code: "CSC 340",
      name: "Information Security",
      description: "Cryptography, network security protocols, ethical hacking fundamentals, vulnerability assessment, and security policy.",
      credits: 3,
      instructor: "Dr. B. Kariuki",
      schedule: "Tue/Thu 3:00 PM",
      department: "Computer Science",
      semester: "Sem 2",
      year: 3,
      enrolled: 25,
      capacity: 35,
      colorVariant: "error",
    },
    {
      id: "csc-s2-mob",
      code: "CSC 350",
      name: "Mobile Application Development",
      description: "Design and development of mobile applications for Android and iOS platforms. Covers UI/UX patterns, APIs, and deployment.",
      credits: 3,
      instructor: "Mr. S. Njoroge",
      schedule: "Mon/Fri 11:00 AM",
      department: "Computer Science",
      semester: "Sem 2",
      year: 4,
      enrolled: 36,
      capacity: 40,
      colorVariant: "tertiary",
    },

    // ── Software Engineering — Sem 1 ─────────────────────────
    {
      id: "c002",
      code: "SWE 201",
      name: "Software Engineering I",
      description: "Introduction to software engineering principles, SDLC models, requirements engineering, and design patterns.",
      credits: 3,
      instructor: "Prof. B. Johnson",
      schedule: "Tue/Thu 1:00 PM",
      department: "Software Engineering",
      semester: "Sem 1",
      year: 2,
      enrolled: 35,
      capacity: 35,
      colorVariant: "tertiary",
    },
    {
      id: "swe-s1-req",
      code: "SWE 211",
      name: "Requirements Engineering",
      description: "Techniques for eliciting, analysing, specifying, and validating software requirements. Covers use cases and user stories.",
      credits: 3,
      instructor: "Dr. N. Oloo",
      schedule: "Wed/Fri 9:00 AM",
      department: "Software Engineering",
      semester: "Sem 1",
      year: 2,
      enrolled: 22,
      capacity: 30,
      colorVariant: "secondary",
    },
    {
      id: "swe-s1-test",
      code: "SWE 221",
      name: "Software Testing & Quality Assurance",
      description: "Unit testing, integration testing, test-driven development, automated testing frameworks, and software quality metrics.",
      credits: 3,
      instructor: "Ms. A. Wambua",
      schedule: "Mon/Thu 2:00 PM",
      department: "Software Engineering",
      semester: "Sem 1",
      year: 3,
      enrolled: 28,
      capacity: 35,
      colorVariant: "primary",
    },

    // ── Software Engineering — Sem 2 ─────────────────────────
    {
      id: "c006",
      code: "SWE 301",
      name: "Software Architecture & Design",
      description: "Advanced software design, architectural patterns, microservices, event-driven design, and system scalability principles.",
      credits: 3,
      instructor: "Dr. F. Chen",
      schedule: "Mon 3:00 PM",
      department: "Software Engineering",
      semester: "Sem 2",
      year: 3,
      enrolled: 20,
      capacity: 30,
      colorVariant: "tertiary",
    },
    {
      id: "swe-s2-devops",
      code: "SWE 311",
      name: "DevOps & Cloud Computing",
      description: "CI/CD pipelines, containerisation with Docker, Kubernetes orchestration, and deploying applications on AWS and GCP.",
      credits: 3,
      instructor: "Mr. K. Cheruiyot",
      schedule: "Tue/Thu 2:00 PM",
      department: "Software Engineering",
      semester: "Sem 2",
      year: 3,
      enrolled: 30,
      capacity: 35,
      colorVariant: "secondary",
    },
    {
      id: "swe-s2-proj",
      code: "SWE 401",
      name: "Software Project Management",
      description: "Agile methodologies, Scrum, project planning, risk management, team dynamics, and software cost estimation.",
      credits: 2,
      instructor: "Prof. L. Gitau",
      schedule: "Fri 1:00 PM",
      department: "Software Engineering",
      semester: "Sem 2",
      year: 4,
      enrolled: 24,
      capacity: 30,
      colorVariant: "primary",
    },

    // ── Mathematics — Sem 1 ──────────────────────────────────
    {
      id: "r002",
      code: "MAT 101",
      name: "Calculus I",
      description: "Limits, continuity, derivatives, techniques of differentiation, and applications including optimisation and related rates.",
      credits: 4,
      instructor: "Prof. H. Maina",
      schedule: "Tue/Thu 11:00 AM",
      department: "Mathematics",
      semester: "Sem 1",
      year: 1,
      enrolled: 30,
      capacity: 40,
      colorVariant: "secondary",
    },
    {
      id: "c008",
      code: "MAT 103",
      name: "Calculus II",
      description: "Integral calculus, techniques of integration, sequences and series, polar coordinates, and introduction to multivariable calculus.",
      credits: 4,
      instructor: "Dr. H. Patel",
      schedule: "Tue/Thu 1:00 PM",
      department: "Mathematics",
      semester: "Sem 1",
      year: 1,
      enrolled: 50,
      capacity: 50,
      colorVariant: "tertiary",
    },
    {
      id: "c003",
      code: "MAT 210",
      name: "Discrete Mathematics",
      description: "Logic, sets, relations, functions, combinatorics, graph theory, and proof techniques applied to computer science problems.",
      credits: 4,
      instructor: "Dr. C. Njuguna",
      schedule: "Mon/Wed 2:00 PM",
      department: "Mathematics",
      semester: "Sem 1",
      year: 2,
      enrolled: 22,
      capacity: 50,
      colorVariant: "primary",
    },

    // ── Mathematics — Sem 2 ──────────────────────────────────
    {
      id: "mat-s2-linalg",
      code: "MAT 202",
      name: "Linear Algebra",
      description: "Vector spaces, linear transformations, matrix factorisation, eigenvalues, eigenvectors, and applications in data science.",
      credits: 3,
      instructor: "Dr. R. Okello",
      schedule: "Mon/Wed 11:00 AM",
      department: "Mathematics",
      semester: "Sem 2",
      year: 2,
      enrolled: 35,
      capacity: 45,
      colorVariant: "secondary",
    },
    {
      id: "mat-s2-prob",
      code: "MAT 211",
      name: "Probability & Statistics",
      description: "Probability theory, random variables, distributions, hypothesis testing, regression analysis, and statistical inference.",
      credits: 3,
      instructor: "Prof. M. Ochieng",
      schedule: "Tue/Thu 9:00 AM",
      department: "Mathematics",
      semester: "Sem 2",
      year: 2,
      enrolled: 40,
      capacity: 50,
      colorVariant: "primary",
    },
    {
      id: "mat-s2-num",
      code: "MAT 301",
      name: "Numerical Methods",
      description: "Numerical solutions to mathematical problems: root finding, interpolation, numerical integration, and solving ODEs.",
      credits: 3,
      instructor: "Dr. T. Wanjala",
      schedule: "Fri 10:00 AM",
      department: "Mathematics",
      semester: "Sem 2",
      year: 3,
      enrolled: 18,
      capacity: 35,
      colorVariant: "tertiary",
    },

    // ── Physics — Sem 1 ──────────────────────────────────────
    {
      id: "r004",
      code: "PHY 101",
      name: "General Physics I",
      description: "Classical mechanics, Newton's laws, energy, momentum, rotational motion, and thermodynamics with laboratory sessions.",
      credits: 4,
      instructor: "Dr. D. Koech",
      schedule: "Mon/Wed/Fri 10:00 AM",
      department: "Physics",
      semester: "Sem 1",
      year: 1,
      enrolled: 38,
      capacity: 45,
      colorVariant: "secondary",
    },
    {
      id: "c009",
      code: "PHY 103",
      name: "General Physics II",
      description: "Electricity, magnetism, electromagnetic waves, optics, and an introduction to modern physics. Includes lab sessions.",
      credits: 4,
      instructor: "Dr. I. Nguyen",
      schedule: "Fri 9:00 AM",
      department: "Physics",
      semester: "Sem 1",
      year: 1,
      enrolled: 20,
      capacity: 40,
      colorVariant: "primary",
    },
    {
      id: "phy-s1-mech",
      code: "PHY 211",
      name: "Classical Mechanics",
      description: "Lagrangian and Hamiltonian mechanics, conservation laws, oscillations, central force problems, and rigid body dynamics.",
      credits: 3,
      instructor: "Prof. O. Simiyu",
      schedule: "Tue/Thu 11:00 AM",
      department: "Physics",
      semester: "Sem 1",
      year: 2,
      enrolled: 15,
      capacity: 30,
      colorVariant: "tertiary",
    },

    // ── Physics — Sem 2 ──────────────────────────────────────
    {
      id: "phy-s2-em",
      code: "PHY 301",
      name: "Electromagnetism",
      description: "Maxwell's equations, electromagnetic fields, wave propagation, radiation, and applications in modern technology.",
      credits: 3,
      instructor: "Dr. A. Rotich",
      schedule: "Mon/Wed 3:00 PM",
      department: "Physics",
      semester: "Sem 2",
      year: 3,
      enrolled: 18,
      capacity: 30,
      colorVariant: "primary",
    },
    {
      id: "phy-s2-qm",
      code: "PHY 311",
      name: "Quantum Mechanics",
      description: "Wave-particle duality, Schrödinger equation, quantum states, uncertainty principle, and introductory quantum computing concepts.",
      credits: 3,
      instructor: "Prof. E. Kiptoo",
      schedule: "Tue/Thu 2:00 PM",
      department: "Physics",
      semester: "Sem 2",
      year: 3,
      enrolled: 12,
      capacity: 25,
      colorVariant: "secondary",
    },
    {
      id: "phy-s2-thermo",
      code: "PHY 321",
      name: "Thermodynamics & Statistical Mechanics",
      description: "Laws of thermodynamics, entropy, free energy, partition functions, and statistical treatment of physical systems.",
      credits: 3,
      instructor: "Dr. C. Barasa",
      schedule: "Wed/Fri 1:00 PM",
      department: "Physics",
      semester: "Sem 2",
      year: 3,
      enrolled: 14,
      capacity: 25,
      colorVariant: "tertiary",
    },

    // ── English — Sem 1 ──────────────────────────────────────
    {
      id: "rc001",
      code: "ENG 101",
      name: "Communication Skills",
      description: "Academic writing, oral presentation, reading comprehension, and professional communication for university students.",
      credits: 2,
      instructor: "Prof. K. Adams",
      schedule: "Mon 9:00 AM",
      department: "English",
      semester: "Sem 1",
      year: 1,
      enrolled: 20,
      capacity: 30,
      colorVariant: "secondary",
    },
    {
      id: "r003",
      code: "ENG 102",
      name: "Academic Writing",
      description: "Advanced composition focusing on research methodology, citation styles, literature reviews, and critical analysis.",
      credits: 3,
      instructor: "Dr. C. Lee",
      schedule: "Wed/Fri 2:00 PM",
      department: "English",
      semester: "Sem 1",
      year: 1,
      enrolled: 25,
      capacity: 35,
      colorVariant: "tertiary",
    },
    {
      id: "eng-s1-lit",
      code: "ENG 201",
      name: "African Literature",
      description: "Survey of African literary works across genres. Explores themes of identity, colonialism, and post-independence society.",
      credits: 3,
      instructor: "Dr. W. Ngugi",
      schedule: "Tue/Thu 10:00 AM",
      department: "English",
      semester: "Sem 1",
      year: 2,
      enrolled: 22,
      capacity: 40,
      colorVariant: "primary",
    },

    // ── English — Sem 2 ──────────────────────────────────────
    {
      id: "eng-s2-tech",
      code: "ENG 211",
      name: "Technical Writing",
      description: "Writing technical reports, documentation, proposals, and manuals. Emphasis on clarity, precision, and audience awareness.",
      credits: 2,
      instructor: "Ms. B. Waweru",
      schedule: "Mon/Wed 11:00 AM",
      department: "English",
      semester: "Sem 2",
      year: 2,
      enrolled: 30,
      capacity: 40,
      colorVariant: "secondary",
    },
    {
      id: "eng-s2-rhet",
      code: "ENG 301",
      name: "Rhetoric & Public Speaking",
      description: "Classical and modern rhetorical theory, persuasive writing, debate, and public speaking for professional contexts.",
      credits: 2,
      instructor: "Prof. J. Muriithi",
      schedule: "Fri 10:00 AM",
      department: "English",
      semester: "Sem 2",
      year: 3,
      enrolled: 28,
      capacity: 35,
      colorVariant: "tertiary",
    },

    // ── History — Sem 1 ──────────────────────────────────────
    {
      id: "hist-s1-africa",
      code: "HIS 101",
      name: "History of Africa",
      description: "Pre-colonial African societies, the slave trade, colonisation, independence movements, and post-colonial African states.",
      credits: 3,
      instructor: "Dr. M. Adhiambo",
      schedule: "Tue/Thu 9:00 AM",
      department: "History",
      semester: "Sem 1",
      year: 1,
      enrolled: 28,
      capacity: 50,
      colorVariant: "primary",
    },
    {
      id: "hist-s1-kenya",
      code: "HIS 201",
      name: "History of Kenya",
      description: "Kenya's pre-colonial history, British colonial rule, the Mau Mau uprising, independence, and contemporary political developments.",
      credits: 3,
      instructor: "Prof. S. Kiplagat",
      schedule: "Mon/Wed 10:00 AM",
      department: "History",
      semester: "Sem 1",
      year: 2,
      enrolled: 35,
      capacity: 50,
      colorVariant: "secondary",
    },

    // ── History — Sem 2 ──────────────────────────────────────
    {
      id: "rc002",
      code: "HIS 202",
      name: "World History",
      description: "Survey of world history from ancient civilisations to the modern era, examining political, economic, and cultural transformations.",
      credits: 3,
      instructor: "Prof. L. Brown",
      schedule: "Wed 11:00 AM",
      department: "History",
      semester: "Sem 2",
      year: 2,
      enrolled: 15,
      capacity: 35,
      colorVariant: "tertiary",
    },
    {
      id: "hist-s2-intl",
      code: "HIS 301",
      name: "International Relations",
      description: "Theories of international relations, diplomacy, foreign policy, the UN system, and current global geopolitical issues.",
      credits: 3,
      instructor: "Dr. P. Langat",
      schedule: "Tue/Thu 1:00 PM",
      department: "History",
      semester: "Sem 2",
      year: 3,
      enrolled: 22,
      capacity: 40,
      colorVariant: "primary",
    },
  ];

  for (const course of coursesData) {
    await prisma.course.upsert({
      where: { id: course.id },
      update: course,
      create: course,
    });
  }

  const registrationsData = [
    { userId: student.id, courseId: "r001" },
    { userId: student.id, courseId: "r002" },
    { userId: student.id, courseId: "r003" },
    { userId: student.id, courseId: "r004" },
  ];

  for (const reg of registrationsData) {
    await prisma.registration.upsert({
      where: { userId_courseId: reg },
      update: {},
      create: reg,
    });
  }

  const cartData = [
    { userId: student.id, courseId: "rc001" },
    { userId: student.id, courseId: "rc002" },
  ];

  for (const ci of cartData) {
    await prisma.cartItem.upsert({
      where: { userId_courseId: ci },
      update: {},
      create: ci,
    });
  }

  const announcementsData = [
    {
      id: "a001",
      title: "Spring Registration Open",
      body: "Registration for the Spring 2025 semester is now open for all continuing students.",
      icon: "campaign",
      iconColor: "tertiary",
    },
    {
      id: "a002",
      title: "Career Fair Next Week",
      body: "Join us in the main hall next Tuesday for the annual engineering career fair.",
      icon: "event",
      iconColor: "secondary",
    },
    {
      id: "a003",
      title: "System Maintenance",
      body: "The portal will be down for scheduled maintenance on Sunday from 2 AM to 4 AM.",
      icon: "info",
      iconColor: "error",
    },
  ];

  for (const ann of announcementsData) {
    await prisma.announcement.upsert({
      where: { id: ann.id },
      update: ann,
      create: ann,
    });
  }

  console.log("Seed completed successfully");
  console.log(`  Student: ${student.email} / password123`);
  console.log(`  Admin: ${admin.email} / password123`);
  console.log(`  Courses: ${coursesData.length}`);
  console.log(`  Registrations: ${registrationsData.length}`);
  console.log(`  Cart items: ${cartData.length}`);
  console.log(`  Announcements: ${announcementsData.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
